name: Check PHP code

on:
    workflow_call:

permissions:
    contents: read

concurrency:
    group: php-unit-${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    php:
        runs-on: ubuntu-latest
        env:
            SW_HOST: localhost:8000
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: shopware
            MAILER_DSN: smtp://localhost:1025
            SW_BASE_PATH: ''
            SELENIUM_HOST: localhost
            SMTP_HOST: localhost
        services:
            database:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: shopware
                options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
                ports:
                    - "3306:3306"
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Cache CS-Fixer
                uses: actions/cache@v4
                with:
                    path: var/cache/php-cs-fixer
                    key: ${{ runner.os }}-php-cs-fixer-${{ hashFiles('vendor-bin/cs-fixer/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-cs-fixer-

            -   name: Cache PHPStan
                uses: actions/cache@v4
                with:
                    path: var/cache/phpstan
                    key: ${{ runner.os }}-phpstan-${{ hashFiles('composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-phpstan-

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   run: make init
            -   run: make check-code
