name: Check JS code and run Jest tests

on:
    workflow_call:

permissions:
    contents: read

concurrency:
    group: js-lint-and-jest-${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    js:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Check JS Code
                run: make check-js-code

            -   name: Run Jest tests
                run: make test-jest
